import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * A preview renders code we did not write — generated by the model, imported
 * from a GitHub repo, or forked from another user's app. It must never run on
 * this origin.
 *
 * `sandbox="allow-scripts allow-same-origin"` is the documented no-op pair: the
 * frame keeps the parent's origin, so it can read `top.localStorage` — where the
 * IAM access and refresh tokens live (lib/hanzo/iam.ts) — and can even remove
 * its own sandbox attribute. A stolen refresh token is account takeover, and an
 * <img> beacon carries it out silently under a CSP that permits `img-src https:`.
 *
 * Source text, not a render: the attribute is what the browser reads, a render
 * test would need the whole builder mounted, and the failure this guards against
 * is someone re-adding one word.
 */

const read = (rel: string) => readFileSync(join(process.cwd(), rel), 'utf8');

/** The sandbox attribute values a file declares. */
const sandboxes = (src: string) =>
  [...src.matchAll(/sandbox=(?:"([^"]*)"|\{`([^`]*)`\})/g)].map((m) => m[1] ?? m[2]);

// The previews that render untrusted HTML through an injected postMessage
// bridge. Neither reaches into `contentDocument`, so neither needs the parent's
// origin for anything.
/**
 * The builder's own pane. It is NOT isolated: `allow-same-origin` is still there,
 * because hover, click-to-select and in-preview navigation run through
 * `contentDocument` and the editor holds the clicked node itself
 * (`selectedElement: HTMLElement`). An opaque origin makes all of that null.
 *
 * So this asserts the weaker property that IS true today — a sandbox exists, so
 * the pane cannot navigate the top frame, open popups or start downloads — and
 * it deliberately does not assert isolation, because asserting a thing that is
 * false is how a known hole starts reading as closed. When the instrumentation
 * moves to the injected bridge, this file is where the move gets proven: delete
 * this block and add the path to ISOLATED.
 */
const HARDENED_NOT_ISOLATED = 'components/editor/preview/index.tsx';

const ISOLATED = [
  'components/preview/live-preview.tsx',
  'components/preview/multipage-preview.tsx',
];

describe('preview isolation', () => {
  it('the builder pane is at least sandboxed, and is still not isolated', () => {
    const found = sandboxes(read(HARDENED_NOT_ISOLATED));

    // Both frames — the double-buffer means one of them is easy to forget.
    expect(found).toHaveLength(2);
    for (const value of found) {
      expect(value).toContain('allow-scripts');
    }

    // Recorded, not asserted away. If this ever stops being true the pane has
    // been isolated, and the test above it should move to ISOLATED.
    expect(found.every((v) => v.includes('allow-same-origin'))).toBe(true);
  });

  it.each(ISOLATED)('%s sandboxes its iframe away from this origin', (file) => {
    const found = sandboxes(read(file));

    // An absent attribute is the WORST case, not a neutral one: no sandbox means
    // every capability, so "no match" must fail rather than vacuously pass.
    expect(found.length).toBeGreaterThan(0);
    for (const value of found) {
      expect(value).toContain('allow-scripts');
      expect(value).not.toContain('allow-same-origin');
    }
  });

  it.each(ISOLATED)('%s accepts messages only from its own frame', (file) => {
    // `event.origin` cannot carry this check once the frame is sandboxed: its
    // origin is the string "null", which every opaque frame on the page shares.
    // The window identity is the only thing unique to our child.
    expect(read(file)).toMatch(/event\.source\s*!==\s*iframeRef\.current\?\.contentWindow/);
  });
});
