import { readFileSync } from 'node:fs';

import { join } from 'node:path';


/**
 * A preview renders code we did not write — generated by the model, imported
 * from a GitHub repo, or forked from another user's app. It must never run on
 * this origin.
 *
 * `sandbox="allow-scripts allow-same-origin"` is the documented no-op pair: the
 * frame keeps the parent's origin, so it can read `top.localStorage` — where the
 * IAM access and refresh tokens live (lib/hanzo/iam.ts) — and can even remove
 * its own sandbox attribute. A stolen refresh token is account takeover, and an
 * <img> beacon carries it out silently under a CSP that permits `img-src https:`.
 *
 * Source text, not a render: the attribute is what the browser reads, a render
 * test would need the whole builder mounted, and the failure this guards against
 * is someone re-adding one word.
 */

const read = (rel: string) => readFileSync(join(process.cwd(), rel), 'utf8');

/** The sandbox attribute values a file declares. */
const sandboxes = (src: string) =>
  [...src.matchAll(/sandbox=(?:"([^"]*)"|\{`([^`]*)`\})/g)].map((m) => m[1] ?? m[2]);

// The previews that render untrusted HTML through an injected postMessage
// bridge. Neither reaches into `contentDocument`, so neither needs the parent's
// origin for anything.
const ISOLATED = [
  // The builder's own pane. It was the last one holding `allow-same-origin`,
  // because hover, click-to-select, theming and scroll-follow ran through
  // `contentDocument`. All of that moved onto the injected bridge, so the flag
  // could go — see e2e/bridge for the browser proof.
  'components/editor/preview/index.tsx',
  'components/preview/live-preview.tsx',
  'components/preview/multipage-preview.tsx',
];

describe('preview isolation', () => {
  it.each(ISOLATED)('%s sandboxes its iframe away from this origin', (file) => {
    const found = sandboxes(read(file));

    // An absent attribute is the WORST case, not a neutral one: no sandbox means
    // every capability, so "no match" must fail rather than vacuously pass.
    expect(found.length).toBeGreaterThan(0);
    for (const value of found) {
      expect(value).toContain('allow-scripts');
      expect(value).not.toContain('allow-same-origin');
    }
  });

  it.each(ISOLATED)('%s accepts messages only from its own frame', (file) => {
    // Either spelled inline, or through `isFrameEvent`, which does the same
    // `event.source !== frame.contentWindow` comparison in one place.
    const src = read(file);
    if (/isFrameEvent\(/.test(src)) {
      expect(src).toMatch(/isFrameEvent\(/);
      return;
    }
    // `event.origin` cannot carry this check once the frame is sandboxed: its
    // origin is the string "null", which every opaque frame on the page shares.
    // The window identity is the only thing unique to our child.
    expect(read(file)).toMatch(/event\.source\s*!==\s*iframeRef\.current\?\.contentWindow/);
  });
});
